#!/bin/bash
############################################################
# repo: src/scripts
# (c) Jim Gerdy (jjg@vundle.com)
# initial: Sep 2012
############################################################

usage() {
cat << EOF
usage: echo [LIST] | $0 options
	functional 'take'
	-h	help, show this message
	-d	delimiter, optional
	-n	number of elements, default=1
	echo A B C | take -n2  	# gives 'B'
EOF
}

N=1
while getopts hd:n: OPTION; do case $OPTION in
	h)	usage; exit 1; ;;
	d)	DELIM=$OPTARG; ;;
	n)	N=$OPTARG; ;;
esac ; done
shift $(( $OPTIND -1 ))
CMDARGS_REMAINING=$0

if [[ -n $DELIM ]] ; then
	OPTIONS=" -F \"$DELIM\" "
fi

  awk $OPTIONS -v ntake=$N '{
	if (ntake>0) {
		printf "%s", $1
		for (idx=2; idx<=ntake; idx++) printf " %s", $idx
	} else if (ntake<0) {
		printf "%s", $(NF+ntake+1)
		for (idx=NF+ntake+2; idx<=NF; idx++) printf " %s", $idx
	}
	printf "\n"
}'

